import = [
  "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]
[env]
term = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true
dynamic_title = true
padding = {x = 10, y=10}
dynamic_padding = true
option_as_alt = "Both"

[font]
size = 18
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "SemiLight" }

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "1", mods = "Command", action = "SelectTab1"},
  { key = "2", mods = "Command", action = "SelectTab2"}
]
